apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
  namespace: rhorizon
  labels:
    app: back
spec:
  replicas: 1
  selector:
    matchLabels: { app: back }
  template:
    metadata:
      labels: { app: back }
    spec:
      serviceAccountName: back-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile: { type: RuntimeDefault }
      containers:
        - name: back
          image: rhorizon/back:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef: { name: back-config }
            - secretRef: { name: back-secret }
          readinessProbe:
            httpGet: { path: /health, port: 8000 }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /health, port: 8000 }
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests: { cpu: "100m", memory: "256Mi" }
            limits:   { cpu: "500m", memory: "512Mi" }
