apiVersion: apps/v1
kind: Deployment
metadata: { name: front, namespace: rhorizon }
spec:
  template:
    spec:
      containers:
        - name: front
          securityContext:
            runAsNonRoot: true
            runAsUser: 101
            allowPrivilegeEscalation: false
            capabilities: { add: [ "NET_BIND_SERVICE" ] }
