apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
spec:
  template:
    spec:
      containers:
        - name: back
          image: rhorizon/back:dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
spec:
  template:
    spec:
      containers:
        - name: front
          image: rhorizon/front:dev
